routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function() {
        Auth::routes();
    });



Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['auth','localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ],
    function()
    {



        Route::get('/', array('as' => 'index', 'uses' => 'AdminController@index'));

        Route::get('users/{user}', ['as' => 'users.edit', 'uses' => 'UserController@edit']);

        Route::patch('users/{user}/update', ['as' => 'users.update', 'uses' => 'UserController@update']);

        Route::resource('announcer', 'AnnouncerController');

        Route::resource('program', 'programController');

        Route::get('setting', 'settingController@edit');

        Route::put('update_setting', 'settingController@update')->name('setting');

    });

app/Program.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Program extends Model
{
    use HasTranslations;
    protected $fillable=[
        'name','img_url_blueprint','description','full_time_program','time_program'
    ];
   public $translatable= ['name','description','full_time_program'];
    public function day()
    {
        return $this->belongsToMany(Day::class,'days_programs','id_program','id_day');
    }
    public function announcer()
    {
        return $this->belongsToMany(Announcer::class,'announcers_programs','id_announcer','id_program');
    }
}

app/Http/Controllers/api/ProgramController.php
<?php

namespace App\Http\Controllers\api;
use App\Announcer;
use App\Day;
use App\Http\Controllers\Controller;

use App\Http\Resources\Days;
use App\Http\Resources\ProgramResource;
use App\Program;
use Carbon\Carbon;
use Illuminate\Http\Request;


class ProgramController extends Controller
{
    public function index(){
        $timeFunction = function ($time){
            $carbon = new Carbon($time->time_program);
            $time->time_program=str_replace(' AM',''.__('title.time_am'),str_replace(' PM',''.__('title.time_pm'),$carbon->format('h:i A' )));
            return $time;
        };
        $program=Program::all()->map($timeFunction);
        return \App\Http\Resources\Program::collection($program);
    }
    public function programByDay(Request $request){

        $day = Day::where('name',$request->day_name)->first();

        if(!$day) abort(404);

        return new Days($day);
    }
    public function programOfAnnouncer(){

        $program = Program::all()->load('announcer');

        return ProgramResource::collection($program);
    }
}

app/Http/Controllers/programController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\messages_programs;
use App\Program;
use Carbon\Carbon;
use Illuminate\Http\Request;

class programController extends Controller
{
    public function index()
    {
        $timeFunction = function ($time){
            $carbon = new Carbon($time);
            return str_replace('AM',''.__('title.time_am'),str_replace('PM',''.__('title.time_pm'),$carbon->format('h:i A' )));
        };
        return view('program.index',compact('timeFunction'));
    }
    public function create()
    {
        return view('program.create');
    }

    public function store(messages_programs $request)
    {
        //
        $program=new Program($request->all());
        if(request()->img_url_blueprint){
            $imageName = time().'.'.request()->img_url_blueprint->getClientOriginalExtension();
            request()->img_url_blueprint->move(public_path('images'), $imageName);
            $program->img_url_blueprint = $imageName;
        }
        $program->save();
        $program->day()->attach($request->day);
        return redirect('program');
    }
    public function show($id)
    {
        $program=Program::find($id);
        return view('program.show')->with(["program"=>$program]);
    }
    public function edit($id)
    {
        //
        $program=Program::find($id);

        return view('program.edit')->with(["program"=>$program]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $program=Program::find($id);
        $program->day()->sync($request->day);
        $program->update(array_filter($request->all(),function ($key){
            return $key != null;
        }));

        if (request()->img_url_blueprint){
            $imageName = time().'.'.request()->img_url_blueprint->getClientOriginalExtension();
            request()->img_url_blueprint->move(public_path('images'), $imageName);
            $program->img_url_blueprint = $imageName;
        }

        $program->save();
        return redirect('program');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $program=Program::find($id);
        $program->delete();
        return redirect('program');
    }
}

resources/views/program/create.blade.php
@extends('layout.dashboard')
@section('content')
    <!--main content start-->
    <div id="page-wrapper">
    <section id="main-content">
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header"><i class="fa fa-file-text-o"></i>@_title('add_program')</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <div class="panel-body">
                            <form class="form-horizontal " method="post" enctype="multipart/form-data" action="{{route('program.store')}}">
                                @csrf

                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('name_program')</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="name[ar]" required>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('name_program_lan')</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="name[en]" required>
                                    </div>
                                </div>


                            <div class="form-group">
                                <label class="col-sm-2 control-label">@_title('image_blueprint')</label>
                                <div class="col-sm-10">
                                    <input type="file" class="form-control" name="img_url_blueprint" required>
                                </div>
                            </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('description')</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="description[ar]" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('description_lan')</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="description[en]" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('fulltime_program')</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="full_time_program[ar]" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('fulltime_program_lan')</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="full_time_program[en]" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('time_program')</label>
                                    <div class="col-sm-10">
                                        <input type="time" class="form-control" name="time_program" required>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">@_title('day')</label>
                                    <div class="col-sm-10">
                                        <select class="form-control"  name="day" required>
                                            @php($var = \Illuminate\Support\Facades\App::getLocale() == 'ar' ? 'name' : 'name_en')
                                            @foreach(\App\Day::all() as $day)
                                                <option value="{{$day->id}}">{{$day->$var}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>


                                <div class="row text-center">
                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <button class="btn btn-default center-block btn-success" type="submit">@_title('add')</button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                </div>
                            </form>
                        </div>

                    </section>

                </div>
            </div>
            <!-- Basic Forms & Horizontal Forms-->


        </section>
    </section>
    <!--main content end-->
    </div>

@endsection

resources/views/program/edit.blade.php
@extends('layout.dashboard')
@section('content')
    <div id="page-wrapper">
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header"><i class="fa fa-file-text-o"></i>@_title('edit')</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <div class="panel-body">
                        <form class="form-horizontal " method="post" enctype="multipart/form-data" action="{{route('program.update',['program'=>$program->id])}}">
                            @csrf
                            @method('put')

                            <div class="form-group">
                                <label class="col-sm-2 control-label">@_title('name_program')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="name" value="{{$program->name}}">
                                </div>
                            </div>


                            <div class="form-group">
                                <label class="col-sm-2 control-label">@_title('image_blueprint')</label>
                                <div class="col-sm-10">
                                    <img class="photoPreview" src="{{url('images/'.$program->img_url_blueprint)}}">
                                    <input type="file" class="form-control" name="img_url_blueprint" value="{{$program->img_url_blueprint}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">@_title('description')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="description" value="{{$program->description}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">@_title('fulltime_program')</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" name="full_time_program" value="{{$program->full_time_program}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">@_title('time_program')</label>
                                <div class="col-sm-10">
                                    <input type="time" class="form-control" name="time_program" value="{{$program->time_program}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">@_title('day')</label>
                                <div class="col-sm-10">
                                    <select class="form-control"  name="day">
                                        @foreach(\App\Day::all() as $day)
                                            <option
                                                value="{{$day->id}}"
                                                @if($day->id == $program->day[0]->id)
                                                    selected
                                                @endif
                                                >{{$day->name}}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <button class="btn btn-default center-block btn-primary" type="submit">@_title('edit')</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </section>

            </div>
        </div>
        <!-- Basic Forms & Horizontal Forms-->

    </section>
</section>
    </div>
@endsection

resources/views/program/index.blade.php
@extends('layout.dashboard')

@section('content')
    <br>
    <br>
    <div id="page-wrapper">
    <section id="main-content">
        <section class="wrapper">
        <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="table table-hover table-responsive">
                </header>
                <table class="table table-bordred table-striped">
                    <thead>

                        <tr>
                        <th>@_title('name_program')</th>
                        <th>@_title('image_blueprint')</th>
                        <th>@_title('description')</th>
                        <th>@_title('fulltime_program')</th>
                        <th>@_title('time_program')</th>
                        <th>@_title('day')</th>
                    </tr>

                    </thead>
                    <tbody>
                    @foreach(\App\Program::all() as $program)

                    <tr>
                        <td>{{$program->name}}</td>
                        <td><img class="picTable" src="{{url('images/'.$program->img_url_blueprint)}}"></td>
                        <td>{{$program->description}}</td>
                        <td>{{$program->full_time_program}}</td>
                        <td>{{$timeFunction($program->time_program)}}</td>
                        <td>
                            @if (LaravelLocalization::getCurrentLocale()  == 'ar')
                            @foreach($program->day()->pluck('name') as $name)
                                {{$name }}
                                <br>
                            @endforeach
                            @elseif(LaravelLocalization::getCurrentLocale()  == 'en')
                                @foreach($program->day()->pluck('name_en') as $name)
                                    {{$name }}
                                    <br>
                                @endforeach
                                @endif
                        </td>
                        <td><a class="btn btn-small btn-primary" href="{{route('program.edit',['$program'=>$program->id])}}">@_title('edit')</a></td>
                        <td><form class="form-horizontal " method="post" action="{{route('program.destroy',['$program'=>$program->id])}}"> @method('DELETE') @csrf <input type="submit" value="@_title('delete')" class="btn btn-small btn-danger"> </form></td>
                    </tr>
                    @endforeach
                </table>
            </section>
        </div>
    </div>
        </section>
    </section>
    </div>
@endsection